### PR TITLE
Gamepad support

### PR DESCRIPTION
**Pull request by MCMrARM**
This is a gamepad support implementation for mcpelauncher-linux.

Bugs & known limitations:
- evdev headers are not exactly included properly, this might cause compile issues.
- splitscreen multiplayer doesn't work and even if I force it to, it's broken.

### CODE REVIEW

**Comment by MCMrARM** [comment]
screenshot from 2017-12-29 15-22-00
Basically how splitscreen works (does not).

**Comment by wiktorek140** [comment]
It is really implemented on android version?

**Comment by MCMrARM** [comment]
I got splitscreen working! :D

**Comment by wiktorek140** [comment]
😊😊 whats was wrong?

**Comment by MCMrARM** [comment]
Mojang was wrong :P
They forgot to enable the scissor test after applying it and the clear was applied to the whole screen instead of a region.

**Comment by MCMrARM** [comment]
@wiktorek140 as for the axis numer 2 issue: does it happen in the mapper ui as well or only in-game?

**Comment by wiktorek140** [comment]
@MCMrARM it only for mapper because my gamepad have 5 axis.  axis 0, axis 1 for left stick, and axis 3, axis 4 for right stick.
and axis 2 is mutual for axis 0 and 4 (event is generated when event for 0 or 4 axis outcome)

**Pull request merged**
