### PR TITLE
Update Installation Instructions

### PR DESCRIPTION
**Pull request by sliceofcode**
:smile:

### CODE REVIEW

**Comment by sliceofcode** [comment]
Note that I had to run this command line to install GLES v2:
```
sudo apt-get install libgles2-mesa-dev:i386
```

**Comment by MCMrARM** [comment]
Ubuntu has the dpkg configured to allow i386 out of the box. Is there any distro which actually needs that dpkg command? I updated the libpng and mesa packages to be -dev already however.

**Comment by MCMrARM** [comment]
lib32bz2 isn't actually used anywhere within the app, so it doesn't really matter.

**Comment by sliceofcode** [comment]
Lubuntu doesn't have i386 out of the box. o/
Thanks, updating my branch.

**Comment by sliceofcode** [comment]
Er... I guess this PR isn't needed anymore.

**Pull request closed without merging**
