### PR TITLE
Modified the underlying hook function

### PR DESCRIPTION
**Pull request by InusualZ**
Modified the underlying hookFunction to comply with the C API (`0` no error or `-1` error). To simplify the test of a hook. Like so `if(!mcpelauncher_hook(...) != 0) printf("Error!")`

Any other suggestion are welcome. Thanks

EDIT: Since, we are going to separate the mod example into his own repository. I deleted the changes from the mod example and only included the hook method changes.

### CODE REVIEW

**Comment by guppy42** [comment]
Good initiative - But it serving as an example I think the code should be vigorously commented - to the level were someone with even just the most rudimentary knowledge of c++/c could follow.


```
//include extra libraries the mod needs, here standard input / output
#include <stdio.h>

//Include the mod api
#include "mcpelauncher_api.h"

//The function we want to hook into - this would normally be a function in the launcher of MCPE it self
// -- link to wiki page explaining how to extract / unmangle exports from libminecraft.so --
int example() {
    return 2;
}

// The is were we store a reference to to the original unhooked function, it must have the same signature as the hooked function.
// this is required even if you do not use it (is this true?)
int (*example_)();

//This is the function you wish to override with - it must have the same signature as the hooked function.
int example_hook() {
    return 100 * example_(); //call the original function as multiply the result by 100
    //you don not have to call the original function, you could entirely override it if you desire.
}

//extern "C" avoids mangling the function names on export
extern "C" void mod_init() {
   //This function is called while the launcher is loading, as such there is no world data yet.
  // use this function so set up you hooks and read configuration data

    if (!mcpelauncher_hook((void*) &example, (void*) &example_hook, (void**) &example_)) {
        //Handle the case were we could not hook the function and inform the user
       //If this happens you properly either misspelled the function name or mojan has changed the funtion name/signature
        printf("Unable to hook `example` function\n");
        return;
    }
  //Let the user know your mod has successfully loaded
    printf("Hello from the example mod! %d\n", example());
}
```

That said I feel that perhaps the example should hook into an actual minecraft function - something simple like changing the MOTD or spamming the chat.

**Comment by InusualZ** [comment]
@guppy42 I was going to do it with an minecraft symbol, the problem is that I can't upload the `libminecraftpe.so`, so, if I can't upload the `*.so`, then I can't link against it and the Mod Example won't work out of the box. So, I decided against it.

About the comments, I thinks It's a great Idea. I'm gonna add the comments

**Comment by MCMrARM** [comment]
In my opinion, it should return 0 on success and -1 on failure to be more compatible with existing C APIs and eventually allow different error codes later.

I agree that the example should show how to hook into Minecraft. However, this example isn't bad for understanding how hooking works, so perhaps we should create a new examples repo and put a few examples there, removing the example from this repo?

**Comment by InusualZ** [comment]
Complied with your requests. I think, we should split the mod example from this repository

**Pull request merged**
