### PR TITLE
Merge the apk-download branch into master

### PR DESCRIPTION
**Pull request by MCMrARM**
Are there still any major issues with the branch?

### CODE REVIEW

**Comment by Tarik02** [comment]
#181

**Comment by Admicos** [comment]
#193

**Comment by AryToNeX** [comment]
#195

**Comment by guppy42** [comment]
Before making this branch master it might be a good idea to create some automated build scripts for various distros as the number of steps to get the launcher up & running are significant

Though I suppose in the long run a PPA would be more helpfull for most people confused by the install process as it can easiler be un/re-installed

**Comment by MCMrARM** [comment]
I'd love to make an official .deb package, but it looks slightly complex.

**Comment by MCMrARM** [comment]
Fixed in-source-directory builds, which should make the build process slightly easier (no need to create a build directory anymore).

**Comment by MCMrARM** [comment]
I guess I'm going to merge it anyways, since 1.1 is pretty much outdated anyways.

**Pull request merged**
