### PR TITLE
Support custom gamepad/joustick axis range. 

### PR DESCRIPTION
**Pull request by wiktorek140**
Remapping for gamepad detected as joystick just by offseting +16 button codes

### CODE REVIEW

**Comment by MCMrARM** [comment]
Are those changes actually needed?

**Comment by wiktorek140** [comment]
Yup. My gamepad is detected as joystick so buttons are negative. Whats more my axis is in range 0-255 so its incopatibile with countig value

**Comment by wiktorek140** [comment]
And print in gamepad mapper somehow fix showing whole window on my pc

**Comment by MCMrARM** [comment]
Well that print won't be merged :P It's a random crash, still needs to be debugged and this is a random sort of fix.

As for the butttons, I'd rather have them on the range 16-32 rather than overlap them with the current gamepad buttons and I have done it like this in https://github.com/MCMrARM/mcpelauncher-linux/commit/06e860ccc83c9c288f45bd0296f72511cfb91365

The code for stick mapping is too hardcoded for your gamepad (-127 for example). I'm not sure why does the OS not report the normal value as 0 and will look into the documentation how to tell what the value should be.

**Comment by MCMrARM** [comment]
Sorry for not actually merging this, but those changes are literally few line changes and actually correcting them would take more work than simply redoing them.

**Pull request closed without merging**
